"""Add missing region_id and blockchain fields

Revision ID: 11191c864b26
Revises: 8d851d177a81
Create Date: 2026-02-21 13:32:56.113887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11191c864b26'
down_revision: Union[str, Sequence[str], None] = '8d851d177a81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sblc_attachments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sblc_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('file_type', sa.Text(), nullable=True),
    sa.Column('file_hash', sa.Text(), nullable=True),
    sa.Column('visibility', sa.Text(), server_default='internal', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sblc_id'], ['sblcs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('ledgers', sa.Column('region_id', sa.String(length=10), server_default='US', nullable=True))
    op.add_column('nodes', sa.Column('region_id', sa.String(length=10), server_default='US', nullable=True))
    op.add_column('users', sa.Column('region_id', sa.String(length=10), server_default='US', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'region_id')
    op.drop_column('nodes', 'region_id')
    op.drop_column('ledgers', 'region_id')
    op.drop_table('sblc_attachments')
    # ### end Alembic commands ###
