"""Add Claim model

Revision ID: 19b342e45681
Revises: bc8addf4ee7a
Create Date: 2026-01-26 13:16:12.683441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '19b342e45681'
down_revision: Union[str, Sequence[str], None] = 'bc8addf4ee7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        DO $$
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'claim_status') THEN
                CREATE TYPE claim_status AS ENUM (
                    'pending', 'accepted', 'rejected'
                );
            END IF;
        END$$;
    """)

    op.create_table('claims',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sblc_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'accepted', 'rejected', name='claim_status', create_type=False), server_default='pending', nullable=False),
    sa.Column('submission_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('documents_json', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sblc_id'], ['sblcs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('claims')
    # ### end Alembic commands ###
