"""Phase 3: Soft deletes and auth prep

Revision ID: 1d12e462693a
Revises: 19b342e45681
Create Date: 2026-01-26 13:50:02.619032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d12e462693a'
down_revision: Union[str, Sequence[str], None] = '19b342e45681'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claims', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('ledgers', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('nodes', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sblcs', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('hashed_password', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'deleted_at')
    op.drop_column('users', 'hashed_password')
    op.drop_column('sblcs', 'deleted_at')
    op.drop_column('nodes', 'deleted_at')
    op.drop_column('ledgers', 'deleted_at')
    op.drop_column('claims', 'deleted_at')
    # ### end Alembic commands ###
