"""Add IP and UserAgent to Audit

Revision ID: 3687c5a0bf92
Revises: 1d12e462693a
Create Date: 2026-01-26 14:00:10.152870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3687c5a0bf92'
down_revision: Union[str, Sequence[str], None] = '1d12e462693a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_events', sa.Column('ip_address', sa.Text(), nullable=True))
    op.add_column('audit_events', sa.Column('user_agent', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audit_events', 'user_agent')
    op.drop_column('audit_events', 'ip_address')
    # ### end Alembic commands ###
