"""Add TokenRevocation model

Revision ID: 5f7baf39c98d
Revises: c5cc8aa8e6ee
Create Date: 2026-01-26 15:24:24.401076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f7baf39c98d'
down_revision: Union[str, Sequence[str], None] = 'c5cc8aa8e6ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_revocations',
    sa.Column('jti', sa.UUID(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('jti')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('token_revocations')
    # ### end Alembic commands ###
