"""Phase 4 models

Revision ID: 702f0d91815d
Revises: 3687c5a0bf92
Create Date: 2026-01-26 14:20:44.886276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '702f0d91815d'
down_revision: Union[str, Sequence[str], None] = '3687c5a0bf92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Manual Enum Updates
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE sblc_status ADD VALUE IF NOT EXISTS 'pending_issuance'")
        op.execute("ALTER TYPE sblc_status ADD VALUE IF NOT EXISTS 'pending_amendment'")
        op.execute("ALTER TYPE claim_status ADD VALUE IF NOT EXISTS 'review_required'")
        op.execute("ALTER TYPE claim_status ADD VALUE IF NOT EXISTS 'payment_approved'")
    op.create_table('approvals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.Text(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('approver_user_id', sa.UUID(), nullable=True),
    sa.Column('role_id', sa.UUID(), nullable=True),
    sa.Column('status', postgresql.ENUM('pending', 'approved', 'rejected', name='approval_status'), server_default='pending', nullable=False),
    sa.Column('step_name', sa.Text(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approver_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sblc_amendments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sblc_id', sa.UUID(), nullable=False),
    sa.Column('change_description', sa.Text(), nullable=False),
    sa.Column('previous_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Text(), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sblc_id'], ['sblcs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sblc_amendments')
    op.drop_table('approvals')
    # ### end Alembic commands ###
