"""Add SBLC model

Revision ID: bc8addf4ee7a
Revises: ac855c775d35
Create Date: 2026-01-26 12:55:08.498700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bc8addf4ee7a'
down_revision: Union[str, Sequence[str], None] = 'ac855c775d35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        DO $$
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'sblc_status') THEN
                CREATE TYPE sblc_status AS ENUM (
                    'draft', 'published', 'issued', 'claimed', 'amended', 'closed'
                );
            END IF;
        END$$;
    """)

    op.create_table('sblcs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ledger_id', sa.UUID(), nullable=False),
    sa.Column('issuing_node_id', sa.UUID(), nullable=False),
    sa.Column('applicant_node_id', sa.UUID(), nullable=False),
    sa.Column('beneficiary_node_id', sa.UUID(), nullable=False),
    sa.Column('reference_number', sa.Text(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('expiry_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', postgresql.ENUM('draft', 'published', 'issued', 'claimed', 'amended', 'closed', name='sblc_status', create_type=False), server_default='draft', nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['applicant_node_id'], ['nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['beneficiary_node_id'], ['nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['issuing_node_id'], ['nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ledger_id'], ['ledgers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference_number')
    )
    op.drop_index(op.f('ix_audit_ledger_created'), table_name='audit_events')
    op.drop_index(op.f('ix_membership_ledger'), table_name='ledger_memberships')
    op.drop_index(op.f('ix_membership_node'), table_name='ledger_memberships')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_membership_node'), 'ledger_memberships', ['node_id'], unique=False)
    op.create_index(op.f('ix_membership_ledger'), 'ledger_memberships', ['ledger_id'], unique=False)
    op.create_index(op.f('ix_audit_ledger_created'), 'audit_events', ['ledger_id', sa.literal_column('created_at DESC')], unique=False)
    op.drop_table('sblcs')
    # ### end Alembic commands ###
