"""Phase 5 blockchain fields

Revision ID: c5cc8aa8e6ee
Revises: 702f0d91815d
Create Date: 2026-01-26 14:54:29.921615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c5cc8aa8e6ee'
down_revision: Union[str, Sequence[str], None] = '702f0d91815d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ledgers', sa.Column('network_id', sa.Text(), nullable=True))
    op.add_column('ledgers', sa.Column('contract_address', sa.Text(), nullable=True))
    op.add_column('nodes', sa.Column('blockchain_identity', sa.Text(), nullable=True))
    
    # Safe Enum Creation
    op.execute("DO $$ BEGIN CREATE TYPE onchain_status AS ENUM('not_anchored', 'pending_anchor', 'anchored', 'failed'); EXCEPTION WHEN duplicate_object THEN null; END $$;")
    
    op.add_column('sblcs', sa.Column('onchain_status', postgresql.ENUM('not_anchored', 'pending_anchor', 'anchored', 'failed', name='onchain_status', create_type=False), server_default='not_anchored', nullable=False))
    op.add_column('sblcs', sa.Column('tx_hash', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sblcs', 'tx_hash')
    op.drop_column('sblcs', 'onchain_status')
    op.drop_column('nodes', 'blockchain_identity')
    op.drop_column('ledgers', 'contract_address')
    op.drop_column('ledgers', 'network_id')
    # ### end Alembic commands ###
