"""Expand SBLC model and lifecycle

Revision ID: d622740d3e8c
Revises: 5f7baf39c98d
Create Date: 2026-01-26 15:34:41.514005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd622740d3e8c'
down_revision: Union[str, Sequence[str], None] = '5f7baf39c98d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sblcs', sa.Column('governing_law', sa.Text(), nullable=True))
    op.add_column('sblcs', sa.Column('applicable_rules', sa.Text(), nullable=True))
    op.add_column('sblcs', sa.Column('product_type', sa.Text(), nullable=True))
    
    # Manually add ENUM values
    op.execute("ALTER TYPE sblc_status ADD VALUE IF NOT EXISTS 'submitted'")
    op.execute("ALTER TYPE sblc_status ADD VALUE IF NOT EXISTS 'under_review'")
    op.execute("ALTER TYPE sblc_status ADD VALUE IF NOT EXISTS 'approved'")
    op.execute("ALTER TYPE sblc_status ADD VALUE IF NOT EXISTS 'claim_submitted'")
    op.execute("ALTER TYPE sblc_status ADD VALUE IF NOT EXISTS 'claim_resolved'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sblcs', 'product_type')
    op.drop_column('sblcs', 'applicable_rules')
    op.drop_column('sblcs', 'governing_law')
    # ### end Alembic commands ###
