"""add_banking_expansion_models

Revision ID: ed7feeb518e4
Revises: 11191c864b26
Create Date: 2026-03-07 23:30:42.806120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ed7feeb518e4'
down_revision: Union[str, Sequence[str], None] = '11191c864b26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('central_bank_gateways',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('region_code', sa.String(length=5), nullable=True),
    sa.Column('portal_url', sa.Text(), nullable=True),
    sa.Column('allowance_limit', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('external_banks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('swift_bic', sa.String(length=11), nullable=True),
    sa.Column('hq_country', sa.String(length=2), nullable=True),
    sa.Column('api_endpoint', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('digital_wallets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('node_id', sa.UUID(), nullable=False),
    sa.Column('wallet_type', postgresql.ENUM('btc', 'eth', 'institutional_vault', name='wallet_type'), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('is_verified_by_bank', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('verifying_bank_id', sa.UUID(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ),
    sa.ForeignKeyConstraint(['verifying_bank_id'], ['nodes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address')
    )
    op.create_table('financial_instruments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('instrument_type', postgresql.ENUM('debt', 'fixed_income', 'index', 'national_debt', name='instrument_type'), nullable=False),
    sa.Column('isin', sa.String(length=12), nullable=True),
    sa.Column('issuer_node_id', sa.UUID(), nullable=True),
    sa.Column('par_value', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('maturity_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('coupon_rate', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('is_national_debt', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['issuer_node_id'], ['nodes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('isin')
    )
    op.create_table('institution_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('node_id', sa.UUID(), nullable=False),
    sa.Column('account_number', sa.String(length=34), nullable=False),
    sa.Column('account_type', postgresql.ENUM('master', 'sub_account', 'nostro', name='account_type'), server_default='master', nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('balance', sa.Numeric(precision=20, scale=4), server_default='0', nullable=False),
    sa.Column('reserved_funds', sa.Numeric(precision=20, scale=4), server_default='0', nullable=False),
    sa.Column('is_nostro', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=True),
    sa.Column('compliance_score', sa.Integer(), server_default='100', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['institution_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_number')
    )
    op.create_table('wire_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sender_account_id', sa.UUID(), nullable=True),
    sa.Column('receiver_account_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('reference', sa.Text(), nullable=True),
    sa.Column('status', postgresql.ENUM('pending', 'held_compliance', 'cleared', 'failed', name='transaction_status'), server_default='pending', nullable=False),
    sa.Column('compliance_check_id', sa.UUID(), nullable=True),
    sa.Column('is_sanction_check_passed', sa.Boolean(), nullable=True),
    sa.Column('is_flagged', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('flag_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('execution_time', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['receiver_account_id'], ['institution_accounts.id'], ),
    sa.ForeignKeyConstraint(['sender_account_id'], ['institution_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wire_transactions')
    op.drop_table('institution_accounts')
    op.drop_table('financial_instruments')
    op.drop_table('digital_wallets')
    op.drop_table('external_banks')
    op.drop_table('central_bank_gateways')
    # ### end Alembic commands ###
